name: run scrapy shopee

on:
  schedule:
    - cron: '*/5 * * * *' # At every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed

      - name: Set up virtual environment
        run: python -m venv venv

      - name: Activate virtual environment
        run: source venv/bin/activate
        
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: execute py script # run main.py
        run: |
          cd ShopeeCrawler/spiders
          echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
          scrapy crawl shopee -o $GITHUB_WORKSPACE/data/$TODAY.json -t json

      - name: Commit and push data
        run: |
          ls
          git config --global user.email "anhtuan.ltqb@gmail.com"
          git config --global user.name "TTAT91A"
          git add data/
          git commit -m "Add data file for $TODAY"
          git push origin main

          
