name: run scrapy shopee

on:
  schedule:
    - cron: '*/5 * * * *' # At every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed

      - name: Set up virtual environment
        run: python -m venv venv

      - name: Activate virtual environment
        run: source venv/bin/activate
        
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Navigate to the spider directory
        run: cd ShopeeCrawler/spiders
        
      - name: execute py script # run main.py
        run: |
          echo "TODAY=$(date +%y-%m-%d)" >> $GITHUB_ENV
          scrapy crawl shopee -o data/$TODAY.json -t json
          
